import { AboutSlint, VerticalBox, Button, TextEdit  } from "std-widgets.slint";
import { Styles } from "styles.slint";

export component MainWindow inherits Window {
    width: 600px;
    height: 800px;
    background: transparent;

    Rectangle {
        background: #101422;
        border-width: 5px;
        border-color: Styles.gradient;
        border-radius: 30px;
    }

    VerticalLayout {
        TextInput {
            vertical-alignment: center;
            horizontal-alignment: right;
        }

        GridLayout {
            padding: Styles.margin;
            spacing: Styles.margin;

            Row {
                Button { text: "7"; }
                Button { text: "8"; }
                Button { text: "9"; }
                Button { text: "-"; }
                Button { text: "+"; }
            }
            Row {
                Button { text: "4"; }
                Button { text: "5"; }
                Button { text: "6"; }
                Button { text: "*"; }
                Button { text: "/"; }
            }
            Row {
                Button { text: "1"; }
                Button { text: "2"; }
                Button { text: "3"; }
                Button { text: "%"; }
                Button { text: "^";   }
            }
            Row {
                Button { text: "0"; }
                Button { text: "."; }
                Button { text: "C"; }
                Button { text: "="; colspan: 2; }

            }
        }
    }
}
